"""
Synthetic detector data generator for rare-event benchmark testing.
"""

import numpy as np
import pandas as pd


def generate_synthetic_detector_data(
    n_samples: int = 5000,
    n_features: int = 20,
    contamination: float = 0.01,
    random_state: int = 42,
):
    """
    Generate synthetic tabular detector data with extreme imbalance (default 1% signal rate).

    Background noise is simulated as multivariate Gaussian with correlated channels.
    Rare signal events are generated by subtle shifts spread across correlated channels,
    mirroring real-world physical detector anomalies.

    Parameters
    ----------
    n_samples : int
        Total number of events to generate.
    n_features : int
        Number of detector channels/features.
    contamination : float
        Proportion of rare signal events (e.g. 0.01 for 1%).
    random_state : int
        Seed for reproducibility.

    Returns
    -------
    df : pandas.DataFrame
        DataFrame of shape (n_samples, n_features) with channel columns.
    labels : numpy.ndarray
        Binary array of shape (n_samples,) where 0 = background, 1 = signal.
    """
    rng = np.random.RandomState(random_state)
    n_signals = max(1, int(n_samples * contamination))
    n_bg = n_samples - n_signals

    # Generate correlated background covariance matrix
    A = rng.randn(n_features, n_features)
    cov = np.dot(A, A.T) * 0.1 + np.eye(n_features) * 0.5
    mean_bg = np.zeros(n_features)

    bg_data = rng.multivariate_normal(mean_bg, cov, size=n_bg)

    # Signal events: multi-channel signature shift
    shift = np.zeros(n_features)
    signal_channels = [0, 1, 2, 3, 4] if n_features >= 5 else list(range(n_features))
    shift[signal_channels] = 2.8

    signal_data = rng.multivariate_normal(mean_bg + shift, cov * 1.5, size=n_signals)

    X = np.vstack([bg_data, signal_data])
    labels = np.hstack([np.zeros(n_bg, dtype=int), np.ones(n_signals, dtype=int)])

    # Shuffle data
    perm = rng.permutation(n_samples)
    X = X[perm]
    labels = labels[perm]

    feature_names = [f"channel_{i+1:02d}" for i in range(n_features)]
    df = pd.DataFrame(X, columns=feature_names)

    return df, labels
